### ISSUE TITLE
`undefined` text when no text inside style or script tag.

### ISSUE THREAD

**Issue by Kal-Aster** [riot/parser#16]
Whenever a `script` or a `style` tag has only whitespace in it, the `text` property is not defined because the inner text is empty.
```html
<script></script>
<!-- or -->
<style>    </style>
```

It would be useful to have access to the `text` property anyway at least to know where the opening tag ends and the closing tag starts.

**Comment by GianlucaGuarini** [comment]
This might be a breaking change since the compiler needs to ignore these tags. Would you mind opening a PR for it? I will be glad to have a look at it

**Comment by GianlucaGuarini** [comment]
Thank you this issue was fixed with your patch in v9.0.0
